djangotask/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^$', views.UsersView.as_view(), name='users-list'),
    url(r'^user/create/$', views.UserCreateView.as_view(), name='users-create'),
    url(r'^user/(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(), name='users-delete'),
    url(r'^user/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='users-detail'),
    url(r'^user/(?P<pk>\d+)/edit/$', views.UserUpdateView.as_view(), name='users-edit'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    birthday = models.DateField(null=True)
    random_number = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('users:users-list')

users/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.template import Context
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

User = get_user_model()


class UsersView(ListView):
    template_name = 'users/users_list.html'
    model = User


class UserDetailView(DetailView):
    template_name = 'users/users_detail.html'
    model = User


class UserCreateView(CreateView):
    template_name = 'users/users_create.html'
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'birthday', 'is_active', 'is_staff', 'is_superuser']


class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users:users-list')


class UserUpdateView(UpdateView):
    template_name = 'users/users_edit.html'
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'birthday', 'is_active', 'is_staff', 'is_superuser']

templates/layouts/default.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'css/users.css' %}">
</head>
<body>
    <div class="wrapper">
    {% block content %}{% endblock %}
    </div>
</body>
</html>

users/templates/users/users_create.html
{% extends 'layouts/default.html' %}

{% block content %}
    <form action="" method="post" class="create-user-form">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'users:users-list' %}">Back</a>
        <button type="submit">Create</button>
    </form>
{% endblock %}

users/templates/users/users_detail.html
{% extends 'layouts/default.html' %}

{% block content %}
    <form action="{% url 'users:users-delete' object.pk %}" method="post" class="create-user-form">
        {% csrf_token %}
        <p><label for="id_username">Username:</label> <span class="helptext">{{ object.username }}</span></p>
        <p><label for="id_first_name">First name:</label> <span class="helptext">{{ object.first_name }}</span></p>
        <p><label for="id_last_name">Last name:</label> <span class="helptext">{{ object.last_name }}</span></p>
        <p><label for="id_email">Email address:</label> <span class="helptext">{{ object.email }}</span></p>
        <p><label for="id_is_active">Active:</label> <span class="helptext">{{ object.is_active }}</span></p>
        <p><label for="id_is_staff">Staff status:</label> <span class="helptext">{{ object.is_staff }}</span></p>
        <p><label for="id_is_superuser">Superuser status:</label> <span class="helptext">{{ object.is_superuser }}</span></p>
        <a href="{% url 'users:users-list' %}">Back</a>
        <button type="submit">Delete</button>
    </form>
{% endblock %}

users/templates/users/users_edit.html
{% extends 'layouts/default.html' %}

{% block content %}
    <form action="" method="post" class="create-user-form">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'users:users-list' %}">Back</a>
        <button type="submit">Update</button>
    </form>
{% endblock %}

users/templates/users/users_list.html
{% extends 'layouts/default.html' %}

{% load allowed bizzfuzz from users_templatetag %}

{% block content %}
    <p>
        <a href="{% url 'users:users-create' %}">Create User</a>
    </p>
    <table class="users-list-table">
        <thead>
            <tr>
                <th>Username</th>
                <th>Birthday</th>
                <th>Eligible</th>
                <th>Random Number</th>
                <th>BizzFuzz</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.birthday }}</td>
                <td>{% allowed user.birthday %}</td>
                <td>{{ user.random_number }}</td>
                <td>{% bizzfuzz user.random_number %}</td>
                <td>
                    <a href="{% url 'users:users-detail' user.pk %}">Details</a>
                    <br>
                    <a href="{% url 'users:users-edit' user.pk %}">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}